/**
 * AI-backed Deal campaign stage generators (AI-FIRST mandate — see TO_FIX.md).
 *
 * Every intelligent stage — angle research, targeting demographic, pitch brief,
 * copy, ad structure, media plan — is generated by a top-tier model through the
 * LLM gateway. There is NO deterministic fallback: if the gateway call fails or
 * times out, the error propagates and the stage produces no output (hard fail).
 * The operator retries. This is intentional — a deterministic scaffold is not an
 * acceptable substitute for reasoning (AI_POLICY §5, TO_FIX foundational rules).
 *
 * Provenance: every generator returns its contract type plus an `aiTrace`
 * (model + prompt sent + raw response + latency) so the operator can inspect
 * exactly what was asked and what came back (Visual Verification principle).
 *
 * Gateway use: all calls go through `generateStructuredObject` with a `ModelName`
 * enum value. No provider SDK is imported here. Zod schemas are kept within the
 * node set the gateway's schema converter supports (object/string/number/boolean/
 * enum/array/record/union/literal/optional).
 */

import { z } from "zod";

import { generateStructuredObject, ModelName } from "@/lib/ai/llm-gateway";

import {
  ANALYST_VOICE_FORBIDDEN,
  buildOfferLines,
  compact,
  detectRedFlags,
  factsDestination,
  QUALIFIER_SUFFIX,
  unique,
  type CampaignStageInputs,
} from "./campaign-generators";
import type {
  DealAdChannelPlan,
  DealAdStructure,
  DealAiGenerationTrace,
  DealCopyPackage,
  DealCtaCopy,
  DealMediaPlan,
  DealPitchBrief,
} from "./campaign-types";
import type { CbPromoIntelligenceRecord } from "./promo-intelligence-types";
import type {
  DealAngleResearch,
  DealResearchCruiseCandidate,
  DealTargetingDemographic,
  RetailDiscoveryBrief,
} from "./research-types";

/** Model used for all Deal reasoning stages (top-tier per AI-FIRST mandate). */
const DEAL_GENERATION_MODEL = ModelName.CLAUDE_4_OPUS;

const DEAL_GENERATION_TIMEOUT_MS = Number(
  process.env.DEAL_GENERATION_TIMEOUT_MS ?? "90000"
);

// ---------------------------------------------------------------------------
// Shared prompt scaffolding
// ---------------------------------------------------------------------------

const GUARDRAILS = `Hard guardrails (never violate):
- Do not invent pricing, onboard credit, cabin availability, or promo eligibility.
- Do not imply a group, hosted event, instructor, workshop, or onboard programming.
- Qualify any perk or savings claim — append: "${QUALIFIER_SUFFIX}"
- Never use: "guaranteed", "lowest price", "free cruise", "always", "no restrictions", "best price ever".
- Base every factual claim only on the cruise facts and promo claims provided.`;

const CUSTOMER_VOICE_RULES = `Customer-voice rules (for any visitor-facing field):
- Write as if speaking to the traveler, not about them.
- Never use analyst/marketing jargon: ${ANALYST_VOICE_FORBIDDEN.join(", ")}.
- Describe the audience as a person ("for travelers who…"), never as a "segment" or "demographic".`;

function factsBlock(input: CampaignStageInputs): string {
  const f = input.cruiseFacts;
  return [
    `Cruise line: ${f.cruiseLine}`,
    `Ship: ${f.shipName}`,
    `Itinerary: ${f.itineraryName}`,
    `Nights: ${f.nights}`,
    `Sail date: ${f.sailDateIso}`,
    f.departurePort ? `Departure port: ${f.departurePort}` : null,
    f.portsOfCall.length ? `Ports of call: ${f.portsOfCall.join(", ")}` : null,
  ]
    .filter(Boolean)
    .join("\n");
}

function promoClaimsBlock(promoRecords?: CbPromoIntelligenceRecord[]): string {
  const claims = (promoRecords ?? []).flatMap((p) => [
    ...p.marketingUse.publicClaimsAllowed,
    ...p.marketingUse.publicClaimsNeedsQualifier,
  ]);
  return claims.length
    ? `Available promo claims (use only these for any savings/perk language):\n- ${claims.join("\n- ")}`
    : "No promo claims provided — do not reference savings, credit, or perks.";
}

function nowIso(input: { generatedAtIso?: string }): string {
  return input.generatedAtIso ?? new Date().toISOString();
}

/**
 * Indirection over the gateway so proof-script tests (run via `tsx`, no mocking
 * framework) can inject a deterministic structured-object generator. Production
 * code never sets this — it defaults to the real gateway call.
 */
type StructuredObjectFn = typeof generateStructuredObject;
let structuredObjectFn: StructuredObjectFn = generateStructuredObject;

/** TEST SEAM: override the gateway generator. Pass no argument to reset. */
export function __setStructuredObjectGeneratorForTests(fn?: StructuredObjectFn): void {
  structuredObjectFn = fn ?? generateStructuredObject;
}

async function generateTraced<TSchema extends z.ZodTypeAny>(args: {
  schema: TSchema;
  system: string;
  prompt: string;
  generatedAtIso: string;
}): Promise<{ object: z.infer<TSchema>; trace: DealAiGenerationTrace }> {
  const startedAt = Date.now();
  const result = await structuredObjectFn({
    model: DEAL_GENERATION_MODEL,
    schema: args.schema,
    system: args.system,
    prompt: args.prompt,
    timeoutMs: DEAL_GENERATION_TIMEOUT_MS,
  });
  const latencyMs = Date.now() - startedAt;
  return {
    object: result.object,
    trace: {
      model: result.modelId,
      promptSent: `SYSTEM:\n${args.system}\n\nPROMPT:\n${args.prompt}`,
      rawResponse: JSON.stringify(result.object, null, 2),
      latencyMs,
      generatedAtIso: args.generatedAtIso,
    },
  };
}

// ---------------------------------------------------------------------------
// Angle research (analyst voice, internal)
// ---------------------------------------------------------------------------

const angleResearchSchema = z.object({
  shipAppeal: z.array(z.string()).min(1),
  amenityHighlights: z.array(z.string()),
  destinationHooks: z.array(z.string()).min(1),
  itineraryPacingNotes: z.array(z.string()),
  nicheAudienceAngles: z.array(z.string()).min(1),
  trendMatches: z.array(z.string()),
  competitorBlindSpots: z.array(z.string()).min(1),
  recommendedPrimaryAngle: z.object({
    title: z.string(),
    rationale: z.string(),
    publicCopyHook: z.string(),
    whyThisFeelsExclusive: z.string(),
  }),
  rejectedAngles: z.array(z.object({ title: z.string(), reason: z.string() })),
  factualGuardrails: z.array(z.string()),
});

export async function generateDealAngleResearchAi(input: {
  candidate: DealResearchCruiseCandidate;
  retailBrief?: RetailDiscoveryBrief;
  generatedAtIso?: string;
}): Promise<DealAngleResearch> {
  const generatedAtIso = nowIso(input);
  const { candidate, retailBrief } = input;

  const system = `You are a cruise retail strategist producing INTERNAL angle research for one
specific sailing. This is analyst voice (notes for the operator and downstream AI),
not customer copy. Find the most specific, defensible reason this exact sailing is
worth promoting to a niche audience — not a generic cruise sale.
${GUARDRAILS}`;

  const prompt = `Sailing facts:
Cruise line: ${candidate.cruiseLine ?? "unknown"}
Ship: ${candidate.shipName ?? "unknown"}
Itinerary: ${candidate.itineraryName}
Destination: ${candidate.destination}
Nights: ${candidate.nights ?? "unknown"}
Sail date: ${candidate.sailDateIso ?? "unknown"}
Departure port: ${candidate.departurePort ?? "unknown"}
Ports of call: ${candidate.portsOfCall.join(", ") || "unknown"}
Ship features: ${(candidate.shipFeatures ?? []).join(", ") || "none provided"}
Amenities: ${(candidate.amenities ?? []).join(", ") || "none provided"}
${
  retailBrief
    ? `\nRetail discovery brief (use as the audience anchor):
Angle: ${retailBrief.retailAngleTitle}
Audience: ${retailBrief.audience.label}
Emotional drivers: ${retailBrief.audience.emotionalDrivers.join(", ")}
Ideal ship features: ${retailBrief.cruiseFit.idealShipFeatures.join(", ")}
Primary hook: ${retailBrief.retailPositioning.primaryHook}`
    : "\nNo retail discovery brief — derive the niche angle from the sailing facts."
}

Produce: ship appeal points, amenity highlights, destination hooks, itinerary pacing
notes, niche audience angles, trend matches, competitor blind spots, one recommended
primary angle (title, rationale, public copy hook, why it feels exclusive), rejected
angles with reasons, and factual guardrails to verify before public copy.`;

  const { object, trace } = await generateTraced({
    schema: angleResearchSchema,
    system,
    prompt,
    generatedAtIso,
  });

  return {
    dealCandidateId: candidate.id,
    generatedAtIso,
    retailDiscoveryBriefId: retailBrief?.id,
    shipAppeal: unique(object.shipAppeal),
    amenityHighlights: unique(object.amenityHighlights),
    destinationHooks: unique(object.destinationHooks),
    itineraryPacingNotes: unique(object.itineraryPacingNotes),
    nicheAudienceAngles: unique(object.nicheAudienceAngles),
    trendMatches: unique(object.trendMatches),
    competitorBlindSpots: unique(object.competitorBlindSpots),
    recommendedPrimaryAngle: object.recommendedPrimaryAngle,
    rejectedAngles: object.rejectedAngles,
    factualGuardrails: object.factualGuardrails,
    sources: [
      {
        title: retailBrief
          ? `Retail discovery brief: ${retailBrief.retailAngleTitle}`
          : "Cruise candidate facts",
        url: "internal://deals-system/research",
        usedFor: "AI niche angle and trip-quality research.",
      },
    ],
    generator: "gpt",
    aiTrace: trace,
  };
}

// ---------------------------------------------------------------------------
// Targeting demographic (analyst voice, internal)
// ---------------------------------------------------------------------------

const targetingSchema = z.object({
  primaryAudience: z.object({
    label: z.string(),
    description: z.string(),
    whyThisCruiseFits: z.string(),
    emotionalDrivers: z.array(z.string()),
    likelyObjections: z.array(z.string()),
  }),
  secondaryAudiences: z.array(
    z.object({
      label: z.string(),
      description: z.string(),
      whyThisCruiseFits: z.string(),
      targetingNotes: z.array(z.string()),
    })
  ),
  nicheKeywords: z.object({
    lifestyle: z.array(z.string()),
    destination: z.array(z.string()),
    shipExperience: z.array(z.string()),
    amenities: z.array(z.string()),
    eventsAndSeasonality: z.array(z.string()),
    trendSignals: z.array(z.string()),
    exclusionKeywords: z.array(z.string()),
  }),
  channelTargeting: z.object({
    meta: z.object({
      interestClusters: z.array(z.string()),
      behaviorSignals: z.array(z.string()),
      creativeHooks: z.array(z.string()),
      audienceWarnings: z.array(z.string()),
    }),
    google: z.object({
      searchThemes: z.array(z.string()),
      keywordIdeas: z.array(z.string()),
      negativeKeywords: z.array(z.string()),
      landingPageIntentNotes: z.array(z.string()),
    }),
    tiktok: z.object({
      creatorAngles: z.array(z.string()),
      trendHooks: z.array(z.string()),
      shortVideoConcepts: z.array(z.string()),
    }),
    email: z.object({
      segmentIdeas: z.array(z.string()),
      subjectLineAngles: z.array(z.string()),
      personalizationNotes: z.array(z.string()),
    }),
  }),
  researchSummary: z.object({
    primaryInsight: z.string(),
    whyNow: z.string(),
    competitorBlindSpot: z.string(),
    positioningStatement: z.string(),
  }),
  confidence: z.object({
    score: z.number(),
    strengths: z.array(z.string()),
    risks: z.array(z.string()),
    needsHumanReview: z.array(z.string()),
  }),
});

export async function generateDealTargetingDemographicAi(input: {
  dealId: string;
  packageId: string;
  candidate: DealResearchCruiseCandidate;
  angleResearch: DealAngleResearch;
  retailBrief?: RetailDiscoveryBrief;
  generatedAtIso?: string;
}): Promise<DealTargetingDemographic> {
  const generatedAtIso = nowIso(input);
  const { candidate, angleResearch, retailBrief } = input;

  const system = `You are a cruise retail audience strategist producing an INTERNAL
Targeting-Demographic resource for one sailing. Analyst voice. Define a specific
audience (more precise than "cruise shoppers"), channel-specific targeting for
Meta/Google/TikTok/email, niche keywords, and honest confidence with risks.
${GUARDRAILS}`;

  const prompt = `Recommended angle (from research): ${angleResearch.recommendedPrimaryAngle.title}
Angle rationale: ${angleResearch.recommendedPrimaryAngle.rationale}
Public copy hook: ${angleResearch.recommendedPrimaryAngle.publicCopyHook}
Niche audience angles: ${angleResearch.nicheAudienceAngles.join(", ")}
Trend matches: ${angleResearch.trendMatches.join(", ")}
Competitor blind spots: ${angleResearch.competitorBlindSpots.join(", ")}

Sailing facts:
Cruise line: ${candidate.cruiseLine ?? "unknown"}
Ship: ${candidate.shipName ?? "unknown"}
Itinerary: ${candidate.itineraryName}
Destination: ${candidate.destination}
Nights: ${candidate.nights ?? "unknown"}
Ports of call: ${candidate.portsOfCall.join(", ") || "unknown"}
${
  retailBrief
    ? `\nRetail discovery brief audience: ${retailBrief.audience.label}
Community signals: ${retailBrief.audience.communitySignals.join(", ")}
Targeting seeds (niche): ${retailBrief.targetingSeeds.nicheKeywords.join(", ")}
Targeting seeds (negative): ${retailBrief.targetingSeeds.negativeKeywords.join(", ")}`
    : ""
}

Always include in exclusionKeywords/negativeKeywords at least: "free cruise", "cruise job".
Always include an audience warning against broad cruise-interest targeting as the primary audience.`;

  const { object, trace } = await generateTraced({
    schema: targetingSchema,
    system,
    prompt,
    generatedAtIso,
  });

  return {
    dealId: input.dealId,
    packageId: input.packageId,
    generatedAtIso,
    primaryAudience: object.primaryAudience,
    secondaryAudiences: object.secondaryAudiences,
    nicheKeywords: object.nicheKeywords,
    channelTargeting: object.channelTargeting,
    researchSummary: object.researchSummary,
    sources: [
      ...angleResearch.sources,
      {
        title: retailBrief
          ? `Retail discovery brief: ${retailBrief.retailAngleTitle}`
          : "Cruise candidate facts",
        url: "internal://deals-system/targeting",
        usedFor: "AI Targeting-Demographic generation.",
      },
    ],
    confidence: object.confidence,
    generator: "gpt",
    aiTrace: trace,
  };
}

// ---------------------------------------------------------------------------
// Pitch brief (customer voice — the research→copy boundary, Phase 9B)
// ---------------------------------------------------------------------------

const pitchBriefSchema = z.object({
  tripSummary: z.string(),
  audienceStatement: z.string(),
  primaryHook: z.string(),
  curatedReason: z.string(),
  sellingFacts: z.array(z.string()).min(3).max(3),
  researchRationale: z.string(),
});

export async function generateDealPitchBriefAi(
  input: CampaignStageInputs
): Promise<DealPitchBrief> {
  const generatedAtIso = nowIso(input);
  const { angleResearch, targetingDemographic, campaignStrategy } = input;

  const system = `You write the customer-voice pitch brief that sits between internal
research and public copy. Your job is to find the ONE emotional hook that makes this
sailing feel chosen for a specific traveler, then express four customer-voice decisions.
Every field except researchRationale must read as something a customer would encounter.
researchRationale is INTERNAL ONLY and must never read like customer copy.
${CUSTOMER_VOICE_RULES}
${GUARDRAILS}`;

  const prompt = `${factsBlock(input)}

${
  campaignStrategy
    ? `Operator-selected campaign hook to preserve:
Hook: ${campaignStrategy.campaignAngle}
Audience: ${campaignStrategy.targetAudience}
Visual angle: ${campaignStrategy.visualAngle}
Targeting keywords: ${campaignStrategy.targetingKeywords.join(", ")}
Do not invent a different central promise.`
    : "No operator-selected campaign hook was saved yet."
}

${
  angleResearch
    ? `Research angle: ${angleResearch.recommendedPrimaryAngle.title}
Public copy hook: ${angleResearch.recommendedPrimaryAngle.publicCopyHook}
Why it feels exclusive: ${angleResearch.recommendedPrimaryAngle.whyThisFeelsExclusive}`
    : "No angle research provided."
}
${
  targetingDemographic
    ? `Primary audience: ${targetingDemographic.primaryAudience.label} — ${targetingDemographic.primaryAudience.description}
Emotional drivers: ${targetingDemographic.primaryAudience.emotionalDrivers.join(", ")}`
    : "No targeting provided."
}
${promoClaimsBlock(input.promoRecords)}

Write:
1. tripSummary — one customer-voice sentence naming nights, ship, and a port.
2. audienceStatement — who this is for, stated as a person ("For travelers who…").
3. primaryHook — the single best reason to care (not a perk list).
4. curatedReason — why this feels selected for them, not broadcast to everyone.
5. sellingFacts — EXACTLY 3 short, qualified, public-safe selling facts; each stands alone.
6. researchRationale — INTERNAL note: which research insights drove these decisions.`;

  const { object, trace } = await generateTraced({
    schema: pitchBriefSchema,
    system,
    prompt,
    generatedAtIso,
  });

  const sellingFacts: [string, string, string] = [
    object.sellingFacts[0],
    object.sellingFacts[1],
    object.sellingFacts[2],
  ];

  return {
    dealId: input.dealId,
    packageId: input.packageId,
    generatedAtIso,
    generator: "gpt",
    tripSummary: object.tripSummary,
    audienceStatement: object.audienceStatement,
    primaryHook: campaignStrategy?.campaignAngle.trim() || object.primaryHook,
    curatedReason: campaignStrategy
      ? `${object.curatedReason} Operator-selected campaign hook: ${campaignStrategy.campaignAngle}.`
      : object.curatedReason,
    sellingFacts,
    researchRationale: campaignStrategy
      ? `${object.researchRationale} Operator-selected campaign hook: ${campaignStrategy.campaignAngle}.`
      : object.researchRationale,
    aiTrace: trace,
  };
}

/**
 * Scan a pitch brief's customer-facing fields for leaked analyst/marketing voice.
 * Surfaced in the workbench for the operator; never auto-fixes. researchRationale
 * is internal and intentionally excluded.
 */
export function validatePitchBriefVoice(brief: DealPitchBrief): string[] {
  const customerFields: Array<[string, string]> = [
    ["tripSummary", brief.tripSummary],
    ["audienceStatement", brief.audienceStatement],
    ["primaryHook", brief.primaryHook],
    ["curatedReason", brief.curatedReason],
    ...brief.sellingFacts.map(
      (fact, i) => [`sellingFacts[${i}]`, fact] as [string, string]
    ),
  ];
  const warnings: string[] = [];
  for (const [field, text] of customerFields) {
    const lower = text.toLowerCase();
    for (const phrase of ANALYST_VOICE_FORBIDDEN) {
      if (lower.includes(phrase)) {
        warnings.push(`${field} uses analyst-voice phrase "${phrase}".`);
      }
    }
  }
  return unique(warnings);
}

// ---------------------------------------------------------------------------
// Copy package (customer voice — sourced from the pitch brief)
// ---------------------------------------------------------------------------

const copySchema = z.object({
  headlineOptions: z.array(z.string()).min(1),
  shortTileCopy: z.string(),
  heroCopy: z.string(),
  whyThisTrip: z.array(z.string()).min(1),
});

export async function generateDealCopyPackageAi(
  input: CampaignStageInputs,
  pitchBrief: DealPitchBrief
): Promise<DealCopyPackage> {
  const generatedAtIso = nowIso(input);
  const { offerLines, agentOnlyNotes } = buildOfferLines(input);

  const system = `You write visitor-safe public copy for a cruise Deal page, built
strictly from the supplied pitch brief. Do not introduce facts or offers not present
in the pitch brief or the listed promo claims.
${CUSTOMER_VOICE_RULES}
${GUARDRAILS}`;

  const prompt = `Pitch brief (your only source of positioning):
Trip summary: ${pitchBrief.tripSummary}
Audience: ${pitchBrief.audienceStatement}
Primary hook: ${pitchBrief.primaryHook}
Curated reason: ${pitchBrief.curatedReason}
Selling facts: ${pitchBrief.sellingFacts.join(" | ")}

${factsBlock(input)}
${promoClaimsBlock(input.promoRecords)}

Write:
1. headlineOptions — 3 distinct headline variants; the FIRST must be the primaryHook.
2. shortTileCopy — one short homepage-tile line.
3. heroCopy — hero paragraph; must contain the trip summary verbatim.
4. whyThisTrip — bullet reasons; MUST include all three selling facts verbatim, plus the curated reason.`;

  const { object, trace } = await generateTraced({
    schema: copySchema,
    system,
    prompt,
    generatedAtIso,
  });

  // Enforce the pitch-brief dependency deterministically so copy can never drift
  // from the locked editorial decisions, regardless of model phrasing.
  const headlineOptions = unique([
    pitchBrief.primaryHook,
    ...object.headlineOptions,
  ]);
  const whyThisTrip = unique([
    ...pitchBrief.sellingFacts,
    pitchBrief.curatedReason,
    ...object.whyThisTrip,
  ]);
  const heroCopy = object.heroCopy.includes(pitchBrief.tripSummary)
    ? object.heroCopy
    : `${pitchBrief.tripSummary} ${object.heroCopy}`.trim();

  const ctaCopy: DealCtaCopy[] = [
    {
      kind: "book_now",
      label: "Book now",
      supportingText: "Go straight to the prepared booking link for this sailing.",
    },
    {
      kind: "email_link",
      label: "Email me the booking link",
      supportingText: "We will send the prepared link so you can book when you are ready.",
    },
    {
      kind: "request_callback",
      label: "Request an agent callback",
      supportingText: "A Leisure Life agent will confirm pricing, cabins, and perks with you.",
    },
  ];

  const publicCopyRedFlags = detectRedFlags([
    ...headlineOptions,
    heroCopy,
    object.shortTileCopy,
    ...whyThisTrip,
    ...offerLines.map((line) => line.text),
  ]);

  return {
    dealId: input.dealId,
    packageId: input.packageId,
    generatedAtIso,
    generator: "gpt",
    headlineOptions,
    shortTileCopy: object.shortTileCopy,
    heroCopy,
    whyThisTrip,
    offerLines,
    ctaCopy,
    publicCopyRedFlags,
    agentOnlyNotes,
    aiTrace: trace,
  };
}

// ---------------------------------------------------------------------------
// Ad structure (internal)
// ---------------------------------------------------------------------------

const adChannelSchema = z.object({
  channel: z.enum(["meta", "google", "tiktok", "email"]),
  primaryAngle: z.string(),
  hooks: z.array(z.string()),
  proofPoints: z.array(z.string()),
  notes: z.array(z.string()),
});

const adStructureSchema = z.object({
  campaignThesis: z.string(),
  channels: z.array(adChannelSchema).min(1),
  nicheKeywords: z.array(z.string()),
  trendKeywords: z.array(z.string()),
  negativeKeywords: z.array(z.string()),
  creativeHypotheses: z.array(z.string()),
});

export async function generateDealAdStructureAi(
  input: CampaignStageInputs
): Promise<DealAdStructure> {
  const generatedAtIso = nowIso(input);
  const { targetingDemographic, angleResearch } = input;

  const offerProofPoints = unique(
    compact([
      ...(input.promoRecords ?? []).flatMap((promo) =>
        promo.marketingUse.publicClaimsAllowed.slice(0, 2)
      ),
      input.cruiseFacts.portsOfCall.length > 0
        ? `Itinerary highlights: ${input.cruiseFacts.portsOfCall.slice(0, 4).join(", ")}.`
        : "",
      `${input.cruiseFacts.nights} nights on ${input.cruiseFacts.shipName}.`,
    ])
  );

  const system = `You design an INTERNAL paid-media campaign structure for one cruise Deal:
a thesis, channel plans for Meta/Google/TikTok/email, keyword sets, and creative hypotheses.
Lead with the niche angle, not a generic price-led cruise pitch.
${GUARDRAILS}`;

  const prompt = `${factsBlock(input)}

${
  angleResearch
    ? `Campaign angle: ${angleResearch.recommendedPrimaryAngle.title}
Rationale: ${angleResearch.recommendedPrimaryAngle.rationale}
Competitor blind spots: ${angleResearch.competitorBlindSpots.join(", ")}`
    : ""
}
${
  targetingDemographic
    ? `Primary audience: ${targetingDemographic.primaryAudience.label}
Meta creative hooks: ${targetingDemographic.channelTargeting.meta.creativeHooks.join(", ")}
Google search themes: ${targetingDemographic.channelTargeting.google.searchThemes.join(", ")}
TikTok creator angles: ${targetingDemographic.channelTargeting.tiktok.creatorAngles.join(", ")}
Email subject angles: ${targetingDemographic.channelTargeting.email.subjectLineAngles.join(", ")}
Niche keywords (lifestyle): ${targetingDemographic.nicheKeywords.lifestyle.join(", ")}`
    : "No targeting provided — derive channel plans from the facts and angle."
}
Verified offer proof points (use these): ${offerProofPoints.join(" | ")}

Produce a plan covering all four channels (meta, google, tiktok, email). Always include
"free cruise" and "cruise job" among negativeKeywords.`;

  const { object, trace } = await generateTraced({
    schema: adStructureSchema,
    system,
    prompt,
    generatedAtIso,
  });

  const channels: DealAdChannelPlan[] = object.channels.map((c) => ({
    channel: c.channel,
    primaryAngle: c.primaryAngle,
    hooks: unique(c.hooks),
    proofPoints: unique([...c.proofPoints, ...offerProofPoints]).slice(0, 4),
    notes: c.notes,
  }));

  return {
    dealId: input.dealId,
    packageId: input.packageId,
    generatedAtIso,
    generator: "gpt",
    campaignThesis: object.campaignThesis,
    channels,
    nicheKeywords: unique(object.nicheKeywords).slice(0, 24),
    trendKeywords: unique(object.trendKeywords).slice(0, 16),
    negativeKeywords: unique([...object.negativeKeywords, "free cruise", "cruise job"]),
    creativeHypotheses: unique(object.creativeHypotheses),
    offerProofPoints,
    aiTrace: trace,
  };
}

// ---------------------------------------------------------------------------
// Media plan (internal)
// ---------------------------------------------------------------------------

const mediaSchema = z.object({
  visualDirection: z.array(z.string()).min(1),
  imageSlots: z
    .array(
      z.object({
        slot: z.string(),
        purpose: z.string(),
        visualConceptPrompt: z.string(),
        requiredSourceAssets: z.array(z.string()),
      })
    )
    .min(1),
  shortVideoConcepts: z.array(
    z.object({
      concept: z.string(),
      hook: z.string(),
      shots: z.array(z.string()),
    })
  ),
  requiredSourceAssets: z.array(z.string()),
});

export async function generateDealMediaPlanAi(
  input: CampaignStageInputs
): Promise<DealMediaPlan> {
  const generatedAtIso = nowIso(input);
  const dest = factsDestination(input.cruiseFacts);

  const system = `You produce an INTERNAL media plan for one cruise Deal: image-slot
visual concept prompts, short-video concepts, and the source assets needed. Concepts
must support the niche angle, be photo-real, and carry no on-image text.
${GUARDRAILS}`;

  const prompt = `${factsBlock(input)}

${
  input.angleResearch
    ? `Angle: ${input.angleResearch.recommendedPrimaryAngle.title}
Public copy hook: ${input.angleResearch.recommendedPrimaryAngle.publicCopyHook}
Destination hooks: ${input.angleResearch.destinationHooks.join(", ")}`
    : ""
}
${
  input.targetingDemographic
    ? `TikTok short-video concepts to draw from: ${input.targetingDemographic.channelTargeting.tiktok.shortVideoConcepts.join(", ")}`
    : ""
}

Produce at least a "hero", a "ship_experience", and a "destination_detail" image slot,
each with a visual concept prompt and the source assets it needs. Include 1-2 short
video concepts with shot lists, and the overall required source asset list.
Anchor destination scenes on: ${dest}.`;

  const { object, trace } = await generateTraced({
    schema: mediaSchema,
    system,
    prompt,
    generatedAtIso,
  });

  return {
    dealId: input.dealId,
    packageId: input.packageId,
    generatedAtIso,
    generator: "gpt",
    visualDirection: unique(object.visualDirection),
    imageSlots: object.imageSlots,
    shortVideoConcepts: object.shortVideoConcepts,
    requiredSourceAssets: unique(object.requiredSourceAssets),
    readiness: "concepts_ready",
    aiTrace: trace,
  };
}
