export const Countries = [
    {"text": "United States", "abbr": "US", "value": 0},
    {"text": "Afghanistan", "abbr": "AF", "value": 1},
    {"text": "Albania", "abbr": "AL", "value": 2},
    {"text": "Algeria", "abbr": "DZ", "value": 3},
    {"text": "Andorra", "abbr": "AD", "value": 4},
    {"text": "Angola", "abbr": "AO", "value": 5},
    {"text": "Anguilla", "abbr": "AI", "value": 6},
    {"text": "Antarctica", "abbr": "AQ", "value": 7},
    {"text": "Antigua and Barbuda", "abbr": "AG", "value": 8},
    {"text": "Argentina", "abbr": "AR", "value": 9},
    {"text": "Armenia", "abbr": "AM", "value": 10},
    {"text": "Aruba", "abbr": "AW", "value": 11},
    {"text": "Australia", "abbr": "AU", "value": 12},
    {"text": "Austria", "abbr": "AT", "value": 13},
    {"text": "Azerbaijan", "abbr": "AZ", "value": 14},
    {"text": "Bahamas", "abbr": "BS", "value": 15},
    {"text": "Bahrain", "abbr": "BH", "value": 16},
    {"text": "Bangladesh", "abbr": "BD", "value": 17},
    {"text": "Barbados", "abbr": "BB", "value": 18},
    {"text": "Belarus", "abbr": "BY", "value": 19},
    {"text": "Belgium", "abbr": "BE", "value": 20},
    {"text": "Belize", "abbr": "BZ", "value": 21},
    {"text": "Benin", "abbr": "BJ", "value": 22},
    {"text": "Bermuda", "abbr": "BM", "value": 23},
    {"text": "Bhutan", "abbr": "BT", "value": 24},
    {"text": "Bolivia", "abbr": "BO", "value": 25},
    {"text": "Bosnia and Herzegovina", "abbr": "BA", "value": 26},
    {"text": "Botswana", "abbr": "BW", "value": 27},
    {"text": "Bouvet Island", "abbr": "BV", "value": 28},
    {"text": "Brazil", "abbr": "BR", "value": 29},
    {"text": "British Indian Ocean Territory", "abbr": "IO", "value": 30},
    {"text": "Brunei Darussalam", "abbr": "BN", "value": 31},
    {"text": "Bulgaria", "abbr": "BG", "value": 32},
    {"text": "Burkina Faso", "abbr": "BF", "value": 33},
    {"text": "Burma", "abbr": "MM", "value": 34},
    {"text": "Burundi", "abbr": "BI", "value": 35},
    {"text": "Cambodia", "abbr": "KH", "value": 36},
    {"text": "Cameroon", "abbr": "CM", "value": 37},
    {"text": "Canada", "abbr": "CA", "value": 38},
    {"text": "Cape Verde", "abbr": "CV", "value": 39},
    {"text": "Cayman Islands", "abbr": "KY", "value": 40},
    {"text": "Central African Republic", "abbr": "CF", "value": 41},
    {"text": "Chad", "abbr": "TD", "value": 42},
    {"text": "Chile", "abbr": "CL", "value": 43},
    {"text": "China", "abbr": "CN", "value": 44},
    {"text": "Christmas Island", "abbr": "CX", "value": 45},
    {"text": "Cocos (Keeling) Islands", "abbr": "CC", "value": 46},
    {"text": "Colombia", "abbr": "CO", "value": 47},
    {"text": "Comoros", "abbr": "KM", "value": 48},
    {"text": "Congo", "abbr": "CG", "value": 49},
    {"text": "Congo, the Democratic Republic of the", "abbr": "CD", "value": 50},
    {"text": "Cook Islands", "abbr": "CK", "value": 51},
    {"text": "Costa Rica", "abbr": "CR", "value": 52},
    {"text": "Cote d'Ivoire", "abbr": "CI", "value": 53},
    {"text": "Croatia", "abbr": "HR", "value": 54},
    {"text": "Cuba", "abbr": "CU", "value": 55},
    {"text": "Cyprus", "abbr": "CY", "value": 56},
    {"text": "Czech Republic", "abbr": "CZ", "value": 57},
    {"text": "Denmark", "abbr": "DK", "value": 58},
    {"text": "Djibouti", "abbr": "DJ", "value": 59},
    {"text": "Dominica", "abbr": "DM", "value": 60},
    {"text": "Dominican Republic", "abbr": "DO", "value": 61},
    {"text": "East Timor", "abbr": "TL", "value": 62},
    {"text": "Ecuador", "abbr": "EC", "value": 63},
    {"text": "Egypt", "abbr": "EG", "value": 64},
    {"text": "El Salvador", "abbr": "SV", "value": 65},
    {"text": "Equatorial Guinea", "abbr": "GQ", "value": 66},
    {"text": "Eritrea", "abbr": "ER", "value": 67},
    {"text": "Estonia", "abbr": "EE", "value": 68},
    {"text": "Eswatini", "abbr": "SZ", "value": 69},
    {"text": "Ethiopia", "abbr": "ET", "value": 70},
    {"text": "Falkland Islands (Malvinas)", "abbr": "FK", "value": 71},
    {"text": "Faroe Islands", "abbr": "FO", "value": 72},
    {"text": "Fiji", "abbr": "FJ", "value": 73},
    {"text": "Finland", "abbr": "FI", "value": 74},
    {"text": "France", "abbr": "FR", "value": 75},
    {"text": "French Guiana", "abbr": "GF", "value": 76},
    {"text": "French Polynesia", "abbr": "PF", "value": 77},
    {"text": "French Southern Territories", "abbr": "TF", "value": 78},
    {"text": "Gabon", "abbr": "GA", "value": 79},
    {"text": "Gambia", "abbr": "GM", "value": 80},
    {"text": "Georgia", "abbr": "GE", "value": 81},
    {"text": "Germany", "abbr": "DE", "value": 82},
    {"text": "Ghana", "abbr": "GH", "value": 83},
    {"text": "Gibraltar", "abbr": "GI", "value": 84},
    {"text": "Greece", "abbr": "GR", "value": 85},
    {"text": "Greenland", "abbr": "GL", "value": 86},
    {"text": "Grenada", "abbr": "GD", "value": 87},
    {"text": "Guadeloupe", "abbr": "GP", "value": 88},
    {"text": "Guam", "abbr": "GU", "value": 89},
    {"text": "Guatemala", "abbr": "GT", "value": 90},
    {"text": "Guernsey", "abbr": "GG", "value": 91},
    {"text": "Guinea", "abbr": "GN", "value": 92},
    {"text": "Guinea-Bissau", "abbr": "GW", "value": 93},
    {"text": "Guyana", "abbr": "GY", "value": 94},
    {"text": "Haiti", "abbr": "HT", "value": 95},
    {"text": "Heard Island and McDonald Islands", "abbr": "HM", "value": 96},
    {"text": "Holy See (Vatican City State)", "abbr": "VA", "value": 97},
    {"text": "Honduras", "abbr": "HN", "value": 98},
    {"text": "Hong Kong", "abbr": "HK", "value": 99},
    {"text": "Hungary", "abbr": "HU", "value": 100},
    {"text": "Iceland", "abbr": "IS", "value": 101},
    {"text": "India", "abbr": "IN", "value": 102},
    {"text": "Indonesia", "abbr": "ID", "value": 103},
    {"text": "Iran", "abbr": "IR", "value": 104},
    {"text": "Iraq", "abbr": "IQ", "value": 105},
    {"text": "Ireland", "abbr": "IE", "value": 106},
    {"text": "Isle of Man", "abbr": "IM", "value": 107},
    {"text": "Israel", "abbr": "IL", "value": 108},
    {"text": "Italy", "abbr": "IT", "value": 109},
    {"text": "Jamaica", "abbr": "JM", "value": 110},
    {"text": "Japan", "abbr": "JP", "value": 111},
    {"text": "Jersey", "abbr": "JE", "value": 112},
    {"text": "Jordan", "abbr": "JO", "value": 113},
    {"text": "Kazakhstan", "abbr": "KZ", "value": 114},
    {"text": "Kenya", "abbr": "KE", "value": 115},
    {"text": "Kiribati", "abbr": "KI", "value": 116},
    {"text": "Kuwait", "abbr": "KW", "value": 117},
    {"text": "Kyrgyzstan", "abbr": "KG", "value": 118},
    {"text": "Laos", "abbr": "LA", "value": 119},
    {"text": "Latvia", "abbr": "LV", "value": 120},
    {"text": "Lebanon", "abbr": "LB", "value": 121},
    {"text": "Lesotho", "abbr": "LS", "value": 122},
    {"text": "Liberia", "abbr": "LR", "value": 123},
    {"text": "Libya", "abbr": "LY", "value": 124},
    {"text": "Liechtenstein", "abbr": "LI", "value": 125},
    {"text": "Lithuania", "abbr": "LT", "value": 126},
    {"text": "Luxembourg", "abbr": "LU", "value": 127},
    {"text": "Macao", "abbr": "MO", "value": 128},
    {"text": "Madagascar", "abbr": "MG", "value": 129},
    {"text": "Malawi", "abbr": "MW", "value": 130},
    {"text": "Malaysia", "abbr": "MY", "value": 131},
    {"text": "Maldives", "abbr": "MV", "value": 132},
    {"text": "Mali", "abbr": "ML", "value": 133},
    {"text": "Malta", "abbr": "MT", "value": 134},
    {"text": "Marshall Islands", "abbr": "MH", "value": 135},
    {"text": "Mauritania", "abbr": "MR", "value": 136},
    {"text": "Mauritius", "abbr": "MU", "value": 137},
    {"text": "Mexico", "abbr": "MX", "value": 138},
    {"text": "Micronesia", "abbr": "FM", "value": 139},
    {"text": "Moldova", "abbr": "MD", "value": 140},
    {"text": "Monaco", "abbr": "MC", "value": 141},
    {"text": "Mongolia", "abbr": "MN", "value": 142},
    {"text": "Montenegro", "abbr": "ME", "value": 143},
    {"text": "Morocco", "abbr": "MA", "value": 144},
    {"text": "Mozambique", "abbr": "MZ", "value": 145},
    {"text": "Namibia", "abbr": "NA", "value": 146},
    {"text": "Nauru", "abbr": "NR", "value": 147},
    {"text": "Nepal", "abbr": "NP", "value": 148},
    {"text": "Netherlands", "abbr": "NL", "value": 149},
    {"text": "New Zealand", "abbr": "NZ", "value": 150},
    {"text": "Nicaragua", "abbr": "NI", "value": 151},
    {"text": "Niger", "abbr": "NE", "value": 152},
    {"text": "Nigeria", "abbr": "NG", "value": 153},
    {"text": "North Korea", "abbr": "KP", "value": 154},
    {"text": "Norway", "abbr": "NO", "value": 155},
    {"text": "Oman", "abbr": "OM", "value": 156},
    {"text": "Pakistan", "abbr": "PK", "value": 157},
    {"text": "Panama", "abbr": "PA", "value": 158},
    {"text": "Papua New Guinea", "abbr": "PG", "value": 159},
    {"text": "Paraguay", "abbr": "PY", "value": 160},
    {"text": "Peru", "abbr": "PE", "value": 161},
    {"text": "Philippines", "abbr": "PH", "value": 162},
    {"text": "Poland", "abbr": "PL", "value": 163},
    {"text": "Portugal", "abbr": "PT", "value": 164},
    {"text": "Qatar", "abbr": "QA", "value": 165},
    {"text": "Romania", "abbr": "RO", "value": 166},
    {"text": "Russia", "abbr": "RU", "value": 167},
    {"text": "Rwanda", "abbr": "RW", "value": 168},
    {"text": "Saint Kitts and Nevis", "abbr": "KN", "value": 169},
    {"text": "Saint Lucia", "abbr": "LC", "value": 170},
    {"text": "Saint Vincent and the Grenadines", "abbr": "VC", "value": 171},
    {"text": "Samoa", "abbr": "WS", "value": 172},
    {"text": "San Marino", "abbr": "SM", "value": 173},
    {"text": "Sao Tome and Principe", "abbr": "ST", "value": 174},
    {"text": "Saudi Arabia", "abbr": "SA", "value": 175},
    {"text": "Senegal", "abbr": "SN", "value": 176},
    {"text": "Serbia", "abbr": "RS", "value": 177},
    {"text": "Seychelles", "abbr": "SC", "value": 178},
    {"text": "Sierra Leone", "abbr": "SL", "value": 179},
    {"text": "Singapore", "abbr": "SG", "value": 180},
    {"text": "Slovakia", "abbr": "SK", "value": 181},
    {"text": "Slovenia", "abbr": "SI", "value": 182},
    {"text": "Solomon Islands", "abbr": "SB", "value": 183},
    {"text": "Somalia", "abbr": "SO", "value": 184},
    {"text": "South Africa", "abbr": "ZA", "value": 185},
    {"text": "South Korea", "abbr": "KR", "value": 186},
    {"text": "Spain", "abbr": "ES", "value": 187},
    {"text": "Sri Lanka", "abbr": "LK", "value": 188},
    {"text": "Sudan", "abbr": "SD", "value": 189},
    {"text": "Suriname", "abbr": "SR", "value": 190},
    {"text": "Sweden", "abbr": "SE", "value": 191},
    {"text": "Switzerland", "abbr": "CH", "value": 192},
    {"text": "Syria", "abbr": "SY", "value": 193},
    {"text": "Taiwan", "abbr": "TW", "value": 194},
    {"text": "Tajikistan", "abbr": "TJ", "value": 195},
    {"text": "Tanzania", "abbr": "TZ", "value": 196},
    {"text": "Thailand", "abbr": "TH", "value": 197},
    {"text": "Togo", "abbr": "TG", "value": 198},
    {"text": "Tonga", "abbr": "TO", "value": 199},
    {"text": "Trinidad and Tobago", "abbr": "TT", "value": 200},
    {"text": "Tunisia", "abbr": "TN", "value": 201},
    {"text": "Turkey", "abbr": "TR", "value": 202},
    {"text": "Turkmenistan", "abbr": "TM", "value": 203},
    {"text": "Turks and Caicos Islands", "abbr": "TC", "value": 204},
    {"text": "Tuvalu", "abbr": "TV", "value": 205},
    {"text": "Uganda", "abbr": "UG", "value": 206},
    {"text": "Ukraine", "abbr": "UA", "value": 207},
    {"text": "United Arab Emirates", "abbr": "AE", "value": 208},
    {"text": "United Kingdom", "abbr": "GB", "value": 209},
    {"text": "Uruguay", "abbr": "UY", "value": 210},
    {"text": "Uzbekistan", "abbr": "UZ", "value": 211},
    {"text": "Vanuatu", "abbr": "VU", "value": 212},
    {"text": "Venezuela", "abbr": "VE", "value": 213},
    {"text": "Vietnam", "abbr": "VN", "value": 214},
    {"text": "Yemen", "abbr": "YE", "value": 215},
    {"text": "Zambia", "abbr": "ZM", "value": 216},
    {"text": "Zimbabwe", "abbr": "ZW", "value": 217},
    
    // Add more countries here...
  ]